export const GET_ENDPOINT_CALL_ACTION = 'GET_ENDPOINT_CALL_ACTION';
export const GET_ENDPOINT_CALL_ACTION_SUCCESS = 'GET_ENDPOINT_CALL_ACTION_SUCCESS';
export const GET_ENDPOINT_CALL_ACTION_FAIL = 'GET_ENDPOINT_CALL_ACTION_FAIL';